### ISSUE TITLE
next issue with useLayoutEffect

### ISSUE THREAD

**Issue by antokhio** [fede4ka1245/ymap3-components#2]
Hi, had an issue with `useLayoutEffect` on next
Prolly need to add `useIsomorphicEffect`

**Comment by fede4ka1245** [comment]
Hey! Thanks for pr!

can you say why u need this effect? why not use smth like this in next js:
```
const YandeMap = () => {
    if (!window) {
       return null;
    }
    
    return (
       // JSX with YMap
    )
}
```

**Comment by antokhio** [comment]
Can try that but I think it's better to have that on library's side... Seems it does not have any side effects and you want plug and play for a library mostly...

**Comment by fede4ka1245** [comment]
Invited u as a collaborator. Merge if u want this funtional :)
