### ISSUE TITLE
Types do not work without `@yandex/ymaps3-types`

### ISSUE THREAD

**Issue by antokhio** [fede4ka1245/ymap3-components#4]
All types are basically `any` unless the `@yandex/ymaps3-types` installed on hosting project...

I think `"@yandex/ymaps3-types": "^0.0.20",`  should be moved from `devDependencies` to `dependencies` in package.json.

But this is a suggestion.... 

And if you install it the typescript isn't happy:
![image](https://github.com/fede4ka1245/ymap3-components/assets/1254168/247ee479-c655-4879-88a5-8c48a07d4c91)

**Comment by fede4ka1245** [comment]
You can install ymaps types in dev dependencies on project where you installs this lib. So, there is no need to add this to dependencies

**Comment by antokhio** [comment]
Yep, but then all nodes are red ;( 

Didn't yet found why that happens...

**Comment by fede4ka1245** [comment]
fix typescript: https://codesandbox.io/p/sandbox/elegant-burnell-wxn9cy
Now types work correctly. You just need run:
`npm i -D @yandex/ymaps3-types@latest `

**Comment by antokhio** [comment]
Hey, nice update, i see you fix quite a lot of stuff, anyways was trying to fix types, end up firing package https://github.com/sbcrmweb/react-ymaps3 

This rectified types are good but still had issues on them :(. 

Currently trying to find time to move script loading under suspense...
